commitizen:
  annotated_tag: true
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: false
  version: 0.1.0
  version_files:
  - .version
  - demo/__init__.py:version
